name: coffee_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.3.1
  dio: ^4.0.6
  get: ^4.6.5
  google_fonts: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.2.1

flutter:

  uses-material-design: true